### ISSUE TITLE
Receive video without sending video

### ISSUE THREAD

**Issue by serips** [webex/webex-js-sdk#1002]
I'm having issues configuring ciscospark sdk to receive video from someone else without sending my video. 

I'm following the sample app from /samples/browser-single.party-call/app.js

And the line 181
` const call = spark.phone.dial(document.getElementById('invitee').value, {constraints});`

at some point calls  createOrJoinLocus(target, options) in call.js
If I set "offerToReceiveVideo" to true in the following snippet (from call.js) then I can successfully receive video without sending. 

`      const recvOnly = !options.constraints.audio && !options.constraints.video;
      options.offerOptions = defaults(options.offerOptions, {
        offerToReceiveAudio: recvOnly || !!options.constraints.audio,
        offerToReceiveVideo: recvOnly || !!options.constraints.video
      });
`

My question is how to send the constraints to achieve that? Or am I doing something totally wrong?

**Comment by mattnorris** [comment]
Hi Sergio! If you uncheck both of the checkboxes in the example, it will set `recvOnly` to `true`. This will constrain audio as well because `recvOnly` is encountered first in the boolean statement. 

If you want to constrain only video, uncheck the video checkbox. That will allow `!!options.constraints.video` to be hit and, I think, give you what you want.
