### ISSUE TITLE
@webex/plugin-meetings: Calling updateVideo and updateAudio results in incorrect mute states reported

### ISSUE THREAD

**Issue by antti2000** [webex/webex-js-sdk#1366]
## Expected Behavior
Calling both meeting.updateVideo and meeting.updateAudio with new local camera and microphone streams within a short period of time (almost consecutively), should result in correct isAudioMuted / isVideoMuted states being sent through members:update callback.

## Current Behavior
Calling both meeting.updateVideo and meeting.updateAudio with new local camera and microphone streams within a short period of time results in incorrect isAudioMuted / isVideoMuted states being sent through members:update callback. The states do not become eventually consistent (through new events) with the sender client. Instead the sender client thinks it is sending both audio and video feeds, but the receiving clients think sender has microphone, camera or both muted (behavior intermittent). Audio stream comes through to the receiving clients pretty much always, video stream sometimes.

If you after a while (> 1s) mute the microphone or camera on the sender client, the audio / video mute states are resolved to correct ones through new events sent to members:update.

Also, adding a delay of approx 50ms - 100ms between the meeting.updateVideo and meeting.updateAudio calls seems to resolve this issue as well.

## Possible Solution (we welcome any logical suggestion)
Each updateVideo/updateAudio call should result in a separate members.update event being sent with the information representing changes occurred due to each individual call. Alternatively, the updates from both calls could potentially be combined into a single result payload that correctly describe the mute audio / video state.

## Steps to Reproduce
1. Start / join meeting with no local media
2. Call updateVideo and updateAudio in a row with local camera and microphone streams
3. Examine the events sent for members:update event for isAudioMuted and isVideoMuted

## Environment Details
* SDK Version 1.80.17
* Node/Browser Version 77.0.3865.90

**Comment by chrisadubois** [comment]
Hi @antti2000 

`updateAudio` and `updateVideo` are unrelated to `isAudioMuted` and `isVideoMuted`. They are not correlated in terms of the SDK members:update event'ing for plugin-meetings.

in your statement you say, "Each updateVideo/updateAudio call should result in a separate members.update event being sent with the information representing changes occurred due to each individual call" -- this is incorrect. neither of these correlate to members update events, they are influenced by media streams only, and only would be specified to media:* events. If the user has previously muted the video or audio, and then they call an updateAudio/Video, the state should persist, the user should not see a members:update event, but the value will remain the same, and video/audio should not be sent if they were muted beforehand.

The reproduction steps do not specify the user was muted beforehand, I tested all the scenarios I could think of locally using the samples app with your reproduction steps as a base. 1. user had audio OR video muted beforehand and calls updateAudio OR updateVideo in rapid succession -- it stayed muted. User did NOT have audio or video muted beforehand and calls updateAudio OR updateVideo in rapid succession -- it stayed unmuted. 

To me, the values on the meeting/members look correct, and I don't believe we'll be sending any extra events.

However, I did see that the updateAudio/Video did not respect the previous mute when done in rapid succession, I will speak with my team and see how we want to approach that.

**Comment by antti2000** [comment]
@chrisadubois Thanks for the quick follow up. Our initialization code does cycle the mute and unmute states (for both microphone and camera), so maybe it is related to that.

However, it does feel like running the updateAudio / updateVideo have an impact on this. Let me see if I can isolate a simple sample that would reproduce the issue.
