### ISSUE TITLE
Auxiliar streams support

### ISSUE THREAD

**Issue by diegofn** [webex/webex-js-sdk#1615]
Hello everyone,

Is there any way to support auxiliar streams in JS SDK as a Windows SDK?

The Windows version is not working right now and I need a multistream support for WebEx.

Best regards.

**Comment by adamweeks** [comment]
@diegofn could you provide a bit more information? Do you need multistream support for sending or receiving?

**Comment by diegofn** [comment]
Hello I need multistream support for receive the auxiliary streams.

**Comment by olivierproffit** [comment]
Hi @diegofn thanks for your feedback. Unfortunately, Multistream is not currently available on our JS SDK.
In order to prioritize your feature request, could you log it into our feature request tool: https://ciscocollaboration.aha.io/session/new ?
This way more people can vote on it and the more likely we'll be able to accelerate its delivery.
Also it will help if you could put in the Aha request the maximum details (type of customers, vertical, expected end user experience, expected developer experience, names of customers if possible). 
Looking forward to delivering you the best experience

**Comment by diegofn** [comment]
Hello Olivier,

I did subscribe to the request tool, I will wait for the authorization to write the future feature.

Best regards.

**Comment by olivierproffit** [comment]
@diegofn  please let me know if you can't access the tool, you can also reach out to me over Webex Teams to discuss your feature request and the associated business case.
