### ISSUE TITLE
Feature Request: Local Recording

### ISSUE THREAD

**Issue by estanescu49727** [webex/webex-js-sdk#1808]
Hello dev team,

We are looking forward to programmatic support for the local recording for Webex Meetings (plugin-meetings). I saw currently recording is done in the cloud and we need it to be saved locally.

In the Record specs you say it is technically possible to record locally from code. Can anybody help with this new feature we need?

Much appreciate.

**Comment by arun3528** [comment]
I would suggest use browser api for local recording 

https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API

**Comment by olivierproffit** [comment]
Hi @estanescu49727  thanks for this feature request and your interest in Webex SDK. As Product Manager, I love hearing your needs. If browser API doesn't work for you, and you still prefer In order to make it more visible, votable by others, and even higher in our backlog, could you post it in our feature request tool with most details possible (expected user flow, use case, business case, ...): https://ciscocollaboration.aha.io/session/new
Thanks

**Comment by estanescu49727** [comment]
@arun3528 I was able to capture the streams join both audio and video and download the blob. But we would like native support from the SDK. It is a good approach nevertheless but browser has its limitation regarding memory use.

**Comment by estanescu49727** [comment]
Thanks everyone.
