### ISSUE TITLE
Webex Meeting - remote audio is silent when remote media is automatically added

### ISSUE THREAD

**Issue by JiandongRuan** [webex/webex-js-sdk#3588]
**Describe the bug**
Remote audio isn't rendered.

**To Reproduce**
1. Modify the [kitchen app](https://webex.github.io/webex-js-sdk/samples/browser-plugin-meetings/) so that it automatically join a meeting and add the remote media. The automation does the following 4 operations programmatically without requiring users clicking the button on the UI:
`createMeeting();
verifyPassword();
joinMeeting();
addMedia();
`
2. Speak at the remote side after the app joins the meeting. The remote audio isn't played back in the kitchen app.

**Expected behavior**
Remote audio should be played.

 - OS: Mac OS X M1
 - Browser Chrome
 - Version 124.0.6367.94
 - Device Type Macbook Pro

**Additional context**
Attached [browser_bot.tar.gz](https://github.com/webex/webex-js-sdk/files/15194882/browser_bot.tar.gz) is the version which I modified from the [kitchen app](https://webex.github.io/webex-js-sdk/samples/browser-plugin-meetings/). Use the following query parameters to pass the meeting information.

`?videoAddress=${MEETING_NUMBER}@webex.com&accessToken=${REPLACE_WITH_YOUR_ACCESS_TOKEN}&password=${MEETING_PASSWORD}`

**Comment by sandiban** [comment]
Hello @JiandongRuan,
Thanks for your patience so far and thanks for sharing the details!
Just to correct, this is not the "Kitchen App", we call it just "Browser SDK test plugin". We call KitchenSink (KS) App for the iOS and Android Mobile test Apps. But I understand what you tried to mean here, I just mentioned it additionally. :)

So, before directly getting into your modified script, we have couple of queries - 

- did you try to join the meeting directly from the Meeting test plugin, basically using the UI buttons and that time, did it work? If you've not tried that, could you try that out and confirm please!
- are you using any wired headphone with the headphone jack of the laptop device or, any bluetooth headphoone during your meeting test? Or, you're just using the Macbook in-built spearker only?
- Could you kindly share us the complete browser log of a test meeting, starting from the very beginning of the JS SDK session, which mean starting from creating a meeting and authenticating yourself using Token, until the stage where remote audio can't be heard.

I've a strong doubt that possibly the remote media is not connected with the meeting. Because I don't know how you implemented it as Remote Media would be automatically connected, but as per the JS SDK workflow - first the media available devices need to be fetched (or, GET) and then those need to be added with the meeting.
Once you share us the complete Browser log .HAR file, this part would be cleared.

Regards!
Sandip

**Comment by JiandongRuan** [comment]
Hello @sandiban it turned out to be the audio autoplay policy in Chrome browser, discussed here https://developer.chrome.com/blog/autoplay/. My issue was fixed by starting chrome browser with `--autoplay-policy=no-user-gesture-required` command line option.

**Comment by sandiban** [comment]
Thanks for the confirmation @JiandongRuan !

Regards!
Sandip
