### ISSUE TITLE
Toggling Receiving Audio & Video Broken

### ISSUE THREAD

**Issue by asynchrony-ringo** [webex/webex-js-sdk#508]
When attempting to call toggleReceivingVideo & toggleReceivingAudio on Spark's call object, strange behavior ends up occurring.

Video - The toggle turns off video permanently [cannot toggle back on].
Audio - The toggle turns off both the receiving and the sending audio permanently.

There is a warning that is displayed in the console when attempting to toggle the video:
```expected video sendonly (locus) to equal sendrecv (local media)```
Though we are unsure that this error has any relevance to the problem.

**Comment by asynchrony-ringo** [comment]
At least part of the problem for audio appears to be in call._changeReceivingMedia. It sets up a Once listener on the call which is never executed.

Currently, it's line 934 in @ciscospark/plugin-phone/src/call.js:
```
this.once(`change:receiving${key === `offerToReceiveAudio` ? `Audio` : `Video`}`, () => resolve());
```

That resolve is never called.

**Comment by ianwremmel** [comment]
What browser are you using? Firefox appears to have some issues with renegotiation (bugzilla to be opened when I have time to provide a minimal test case)

**Comment by jasonmcbaird** [comment]
Hey, Ian, we've been devving in Chrome.

Today we went hunting for this bug because we've got three stories blocked on it. We started comparing to the old example app (https://ciscospark.github.io/spark-js-sdk/app/#/?_k=2cgyhc). It turns out audio toggle works there, so we're gonna replicate that ourselves.

But neither our app nor the old example app can toggle receiving video back on. The first time you start receiving video, it works. You can stop receiving video whenever, no problem. However, the second time you start receiving video, it never shows up.

In our app, the video freezes if you already had a video feed or goes black if you didn't. In the old sample app, the video feed disappears.

**Comment by asynchrony-ringo** [comment]
Okay, so, we've now got our app's audio working the same way as the old example app:

When you toggleReceivingAudio() when audio is on, it'll turn the audio off, but the promise never resolves and we do not see an update to call.receivingAudio. We have to toggle the video ON in order to see the promise resolve and the call updated. When we do toggle the video on, we can then turn audio back on immediately.

**Comment by ianwremmel** [comment]
So, I think this bug is because, once video is toggled off, toggling it back on negotiates for a new stream. 

For now, the fix should be 

```js
call.on(`change:remoteVideoStream`, () => {
  document.getElementById(`#remote-view`).srcObject = call.remoteVideoStream;
});
```

**Comment by bzang** [comment]
@asynchrony-ringo and @ianwremmel , can we close this ticket?
