### ISSUE TITLE
After token expires sdk still keeps canAuthorized to true 

### ISSUE THREAD

**Issue by arun3528** [webex/webex-js-sdk#691]
canAuthorized is still true for the first refresh . second refresh makes it false 

Steps to clean the local storage 
credentials.authorization = credentials.Credentials['@'].supertoken || {};
credentials.authorization.refresh_token_expires = Date.now() - 24 * 60 * 60 * 1000;
credentials.authorization.refresh_token = 'this is not a valid refresh token';

**Comment by ianwremmel** [comment]
canAuthorize is intended to always be true if there is a valid refresh token. Are you seeing a case where the refresh token disappears but canAuthorize is still true?

**Comment by arun3528** [comment]
Yep if you manually change credentials.authorization.refresh_token_expires to expire and refresh the page it stays true when you refresh the page once , second refresh makes it false

**Comment by ianwremmel** [comment]
ok. yea, that's because `refresh_token_expires` is meaningless. Every time a successful refresh occurs, the server-stored expire time gets extended, but we don't get the new `refresh_token_expires_in` value, so there's no way to update `refresh_token_expires`. We should probably just get rid of the `refresh_token_expires` and `refresh_token_expires_in` fields. 

I'm not quite sure what's causing the behavior you're seeing, but just playing with `refresh_token_expires` probably isn't the right way to simulate whatever it is you're trying to prove.

**Comment by shailesingh** [comment]
@ianwremmel, I am also facing similar issue after upgrading to 1.9.0 OR 1.6.0 OR 1.0.0. My scenario is initialise ciscospark while loging in to Spark Care app. Once my login is successful, credentials and device information gets written in localStorage as we are using LocalStorageStoreAdapter. After half an hour I close my Spark Car app (No sign out just close the tab). The token which I used will expire after 2 hours. Now if I try to load Spark care app again after 3 hours by passing new token, SDK still reading the information from local storage and throwing following error.
Current state cannot produce an access token (credentials.js)

If I clear my local storage entry it work fine. Please let me know If I am missing something.

In 0.7 access_token was not stored in local Storage.

**Comment by ianwremmel** [comment]
@shailesingh how/why are you passing a new token? When you set a new token, it should be written to localStorage, rather than reading the value from localStorage.

**Comment by shailesingh** [comment]
I am passing new token on refresh like this.
constructCiscoSpark (options) {
		const deviceKeyName = options.deviceKeyName ? options.deviceKeyName : 'ciscospark-mv';
		return new CiscoSpark({
			credentials: options.credentials,
			config: {
				storage: {
					boundedAdapter: new LocalStorageStoreAdapter(`${deviceKeyName}`)
				},
				credentials: {
					oauth: {
						client_id: options.client_id,
						client_secret: options.client_secret
					}
				},
				trackingIdPrefix: 'spark-care-desktop'
			}
		});
	}

Whenever I refresh I initialise spark again by passing my new token as above.

**Comment by ianwremmel** [comment]
ok, are you using the `ciscospark` package or loading a bunch of plugins yourself? If you're loading your own plugins, are you using `@ciscospark/plugin-authorization-browser`? https://ciscospark.github.io/spark-js-sdk/guides/browsers/#authorization-code-grant explains how to supply a refresh callback for token refresh (we now discourage putting the client secret in the web browser). 

Generally speaking, you shouldn't need to create a new spark instance when refreshing the access token. If you're doing token refresh outside of the sdk, then you could probably eliminate the client secret and stop using localstorage entirely

**Comment by shailesingh** [comment]
@ianwremmel 
1) We are using ciscospark and this brings in @ciscospark/plugin-authorization-browser
2) We are not creating a new instance on token refresh. My understanding is sdk will refresh token by itself and use it. For spark care external use we do refresh token our self but do not pass to sdk.
3) We are using localstorage plugin because we do not want to get device created  every time when user does browser refresh.

The scenario which I am trying to explain is as follows.
a) User logs in to spark care, after authorization from CI SSO page, we load the care app and create new instance of the Spark as I explained earlier using sdk.

b) Once Spark instance is created, we register phone using "ciscoSpark.phone.register()". When we do this I see an entry is created in localStorage having credentials and device. After this we do device registration using "ciscoSpark.internal.device.register()". 

c) This completes the Spark initialization and Spark Care web app loads. After this if user keep on refreshing the browser (This will create a new spark instance every time), seems like spark sdk does not take the token which we pass while creating the spark instance rather it uses from localStorage.

d) Now Say, user closes the browser. Entry in localStorage is still there, and the token stored in localStorage get expired after X time. Once password is expired, same user opens a new tab and try to login, this time when we try to create spark instance and register phone it tries to read token from localStorage and because password is expired it gives "Current state cannot produce an access token (credentials.js)" error.

Sorry for long message.

**Comment by ianwremmel** [comment]
Point 2: The sdk handles refresh itself, but you now must provide your own refresh callback. Since we're discouraging you from putting the client secret in your browser, you need to provide a refresh callback that does one of the following

- use the client secret anyway to call CI refresh api explicitly
- make an api call to your backend with the refresh token that will give you a new access token (in this case, the client secret would be protected by your backend
- use `@ciscospark/plugin-authorization-browser-first-party` which provides first-class support for in-browser token refresh (though may not be entirely compatible with the `ciscospark` package at this time - we really are trying to discourage putting the client secret in the browser).

Point 3: `ciscospark` uses the localStorage plugin automatically

`phone.register()` calls `internal.device.register()`, so there should be no need to call `internal.device.register()` explicitly

"Current state cannot produce an access token (credentials.js)" implies you're missing at least on of `refresh_token` or `refreshCalback`.

**Comment by shailesingh** [comment]
@ianwremmel , Can we please have a quick meeting with you as per convenience because I am still not understanding what are we doing wrong.
