### ISSUE TITLE
TypeError: Property 'expires' must be of type number. Tried to set xxxxx

### ISSUE THREAD

**Issue by fusionconsulting** [webex/webex-js-sdk#737]
I'm attempting to implement this into a Laravel app. The auth process is working and I am able to exchange the access code for an access token via an OAuth call on the PHP server. I'm then able to redirect back with the token in the URL which is removed as expected and replaced with state and expires. The problem is the URL looks like this:

http://xyz.com/video/chat#state=e30&expires=1510761245

The console shows an error at the point of initialisation:

TypeError: Property 'expires' must be of type number. Tried to set 1510761245

Any ideas what could be causing this error?

**Comment by ianwremmel** [comment]
@fusionconsulting ciscospark parses the url for oauth2 parameters; in other words, it's expecting `expires_in`, not `expires`. We'll definitely work on handling this case (if nothing else, `expires` should have been ignored), but the short-term fix for you would be to send `expires_in` instead of `expires` to your browser. (note that `expires_in` is measured in seconds).

**Comment by biaalvar** [comment]
Hello, we wanted to verify whether this is still an issue for you and whether the suggested work around was suitable. Thank you

**Comment by olivierproffit** [comment]
@fusionconsulting we close this ticket, hope the workaround we proposed worked for you. Feel free to comment. Thanks
